PROJECT_DIR = "/home/sungs/workspace/synthetic_route_generation"
RESOURCE_DIR = f"{PROJECT_DIR}/resource"
RAW_DATA_DIR = f"{RESOURCE_DIR}/schneider50k"
PROCESSED_DATA_DIR = f"{RESOURCE_DIR}/schneider50k"
CHECKPOINT_DIR = f"{RESOURCE_DIR}/checkpoint"